### ISSUE TITLE
properties inheritance

### ISSUE THREAD

**Issue by 926** [AlexBacich/sticky-headers-table#1]
Hi,
Does this package inherit the properties of DataTable, such as onSelectChange ?

rows: items
    .map(
        (itemRow) => DataRow(
            onSelectChanged: (bool selected) {
                if (selected) {
                    log.add('row-selected: ${itemRow.index}');
                }
            },
            cells: [
                // ..
            ],
        ),

**Comment by AlexBacich** [comment]
Hey, not quite. It uses its own engine. What logic are you trying to
implement, maybe I can help there.

You can actually use builder method for content cells and wrap widgets into
tap listeners. Check advanced example in repo.

Alex

пн, 4 нояб. 2019 г., 12:48 Pierre notifications@github.com:

**Comment by 926** [comment]
thanks, I had a look, it is feasible but less intuitive,
Great repo anyway
