### ISSUE TITLE
Is there a way to align the text of the rowsTitle/columnsTitle

### ISSUE THREAD

**Issue by BenPoell** [AlexBacich/sticky-headers-table#16]
Is there a way to align the text in rowsTitle/columnsTitle left or right?

![image](https://user-images.githubusercontent.com/24900930/96682758-92374b80-1379-11eb-9d13-eb392ef0e2ee.png)

I tried with Align-Widget and also with TextAlign. Another try was adding a row but none of those alignments worked. Is it somehow overruled by the FittedBox-Widget?

```
  List<Widget> _makeTitleRow() {
    return viewModel.answerScaleItems
        .map((AssessmentExecutionAnswerScaleItem scaleItem) => Row(
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Align(
                  alignment: Alignment.centerLeft,
                  child: Text(scaleItem.description,
                      textAlign: TextAlign.left,
                      style: themeData.textTheme.bodyText1),
                ),
              ],
            ))
        .toList();
  }
```

**Comment by alexbaramilis** [comment]
Hi Ben,

As of pull request #15 (hasn't been published on pub.dev yet):

The alignment of the cell contents can be customized using the cellAlignments property of StickyHeadersTable. Use:

CellAlignments.base: Default alignment value (Alignment.center).
CellAlignments.uniform: Same alignment for each cell.
CellAlignments.fixed: Same alignment for each content cell, but different alignment for the sticky column, row and legend.
CellAlignments.variableColumnAlignment: Different alignment for each column.
CellAlignments.variableRowAlignment: Different alignment for each row.
CellAlignments.variable: Different alignment for every cell.

You can copy the table_sticky_headers.dart from the master branch into your project until Alex publishes the new updates.

**Comment by alexbaramilis** [comment]
For your question you probably need:

CellAlignments.fixed(
    contentCellAlignment: Alignment.centerRight,
    stickyColumnAlignment: Alignment.centerLeft,
    stickyRowAlignment: Alignment.centerRight,
    stickyLegendAlignment: Alignment.centerLeft,
)

Adjust .centerLeft/.centerRight accordingly.

**Comment by AlexBacich** [comment]
Released new version of sticky table, it includes CellAlignments.

**Comment by BenPoell** [comment]
Thanks, appreciate it! Tested and working!
