### ISSUE TITLE
Example of CellDimensions.fixed usage

### ISSUE THREAD

**Issue by chrisvdb** [AlexBacich/sticky-headers-table#17]
Would it be possible to provide a small example on how to use CellDimensions.fixed? I'm using the version published on pub.dev.

I'm basing my table on the decorated_example.dart example, but have a hard time figuring out how to best adjust the content cells' dimensions to my needs.

I want to use the opportunity to thank you for a very useful package!

**Comment by alexbaramilis** [comment]
Hi Chris,

The version on pub.dev is not the latest one so it doesn't contain the new constructors for CellDimensions.

You can either copy the 'table_sticky_headers.dart' file from the master branch here on Github into your project and use:

StickyHeadersTable(
    cellDimensions: CellDimensions.fixed(
        contentCellWidth: 200.0,
        contentCellHeight: 50.0,
        stickyLegendWidth: 200.0,
        stickyLegendHeight: 50.0,
    ),

or if you want to stick with the version from pub.dev, just use the deprecated constructor (without the .fixed):

StickyHeadersTable(
    cellDimensions: CellDimensions(
        contentCellWidth: 200.0,
        contentCellHeight: 50.0,
        stickyLegendWidth: 200.0,
        stickyLegendHeight: 50.0,
    ),

You will get a deprecated warning, but you can suppress it if you want.

Let me know if you have any more questions!

**Comment by chrisvdb** [comment]
Thank you, that was helpful. Got it to work.

Are you planning to release the latest version on pub.dev?

**Comment by AlexBacich** [comment]
Will do today.

**Comment by AlexBacich** [comment]
Done uploading. @alexbaramilis Thanks a lot for your contribution.

**Comment by alexbaramilis** [comment]
Happy to help :)
