### ISSUE TITLE
Scroll Error

### ISSUE THREAD

**Issue by tongyangsheng** [AlexBacich/sticky-headers-table#19]
When I scroll to boundary, I found scroll offset can not keep, one scrollerView will Return to initial position, any suggestion?
![image](https://user-images.githubusercontent.com/32046282/100954909-7fa35b00-3550-11eb-82c3-00c8d2160c7e.png)

**Comment by AlexBacich** [comment]
Unfortunately, I haven't found a good solution for this. 
Several options: 
1. Force scroll behavior as on Android (don't allow overscroll as on  iOS). Wouldn't be that nice but will solve the issue. 
2. Somehow monitor state when user has started scroll and haven't finished that. And repeatedly send message to controllers about position change (with same position). Need to see how to get such events.

**Comment by AlexBacich** [comment]
Another solution, later on I will add this parameter. 

Restrict overscroll in table. 
For that change the code to something like that. 

ListView.builder(
                  shrinkWrap: true,
                  physics: const ClampingScrollPhysics(),
....
);

**Comment by tongyangsheng** [comment]
@AlexBacich thank you for response, I have set parameter 'physics' to 'ClampingScrollPhysics()' which can solved this problem. But I found BouncingScrollPhysics is more suitable for iOS platform. The options 2 which you mentioned is a good plan, I will try it.🚀
