### ISSUE TITLE
Can't we edit cells ? 

### ISSUE THREAD

**Issue by ganeshchenniah** [AlexBacich/sticky-headers-table#21]
Hi ,

I m looking for a package ,where we can copy paste content to the sheet . Is it possible here ?

Regards,
GaneshC

**Comment by AlexBacich** [comment]
Hey, editing is not fully supported but possible. There are gesture detectors added in 2.0 update which you can use to bring sort or popup and let users edit content value there. Update your dataset in setState method and you are done.
