### ISSUE TITLE
add another widget instead of textfield 

### ISSUE THREAD

**Issue by kareemX** [AlexBacich/sticky-headers-table#26]
Hi
Is there a way to add another widget instead of textfield 
I wanna add a dropdownmenubutton in one of the Sills and an image preview in another Sill is that possible?

**Comment by AlexBacich** [comment]
Sure - you can put any widgets inside cells, not just texts.

**Comment by kareemX** [comment]
ya I see that but unfortunately the whole table has to be the same widget, but I want a column of ammm colored Containers and a column of say images and another column of TextFields and so on I mean different widgets different columns.
