### ISSUE TITLE
Table doesn't center

### ISSUE THREAD

**Issue by igloo12** [AlexBacich/sticky-headers-table#27]
I am trying to center the table like below but it doesn't have any effect on the table 

```
 @override
  Widget build(BuildContext context) {
    return Center(
        child: StickyHeadersTable(
      columnsLength: titleColumn.length,
      rowsLength: titleRow.length,
      columnsTitleBuilder: (i) => Text(titleColumn[i]),
      rowsTitleBuilder: (i) => Text(titleRow[i]),
      contentCellBuilder: (i, j) => Text(data[i][j]),
      legendCell: Text('Proof data'),
    ));
  }
```

**Comment by AlexBacich** [comment]
Can you show full context? I don't think there's problem with centering table. Rather need to look in what context it is set. 

Also, you can wrap table with fixed size and then center it. It should do the trick.
