### ISSUE TITLE
ScrollController not attached

### ISSUE THREAD

**Issue by peter9teufel** [AlexBacich/sticky-headers-table#28]
Hi,
your sticky header table works like a charm with version 1.2.0 but it seems as if the custom scroll controllers feature in version 2.0.0 has some issues.
I did not change the implementation of the table as we do not need custom scroll controllers, when the user clicks a header field a details page is pushed on the Navigator, when this page is closed scrolling no longer works as expected and the log states that it tries to update scroll positions on scroll controllers that are not attached to a scroll view. The exact same code works fine with sticky-header-table version 1.2.0

`
flutter: The following assertion was thrown while handling a gesture:
flutter: ScrollController not attached to any scroll views.
flutter: 'package:flutter/src/widgets/scroll_controller.dart':
flutter: Failed assertion: line 171 pos 12: '_positions.isNotEmpty'
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      ScrollController.jumpTo
package:flutter/…/widgets/scroll_controller.dart:171
flutter: #3      _SyncScrollController.processNotification
package:table_sticky_headers/table_sticky_headers.dart:348
flutter: #4      _StickyHeadersTableState.build.<anonymous closure>
package:table_sticky_headers/table_sticky_headers.dart:272
flutter: #5      Element.visitAncestorElements
package:flutter/…/widgets/framework.dart:3966
flutter: #6      Notification.dispatch
package:flutter/…/widgets/notification_listener.dart:138
flutter: #7      DragScrollActivity.dispatchScrollUpdateNotification
package:flutter/…/widgets/scroll_activity.dart:451
flutter: #8      ScrollPosition.didUpdateScrollPositionBy
package:flutter/…/widgets/scroll_position.dart:870
flutter: #9      ScrollPosition.setPixels
package:flutter/…/widgets/scroll_position.dart:276
flutter: #10     ScrollPositionWithSingleContext.setPixels
package:flutter/…/widgets/scroll_position_with_single_context.dart:82
flutter: #11     ScrollPositionWithSingleContext.applyUserOffset
package:flutter/…/widgets/scroll_position_with_single_context.dart:124
flutter: #12     ScrollDragController.update
package:flutter/…/widgets/scroll_activity.dart:380
flutter: #13     ScrollableState._handleDragUpdate
package:flutter/…/widgets/scrollable.dart:600
flutter: #14     DragGestureRecognizer._checkUpdate.<anonymous closure>
package:flutter/…/gestures/monodrag.dart:436
flutter: #15     GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:182
flutter: #16     DragGestureRecognizer._checkUpdate
package:flutter/…/gestures/monodrag.dart:436
flutter: #17     DragGestureRecognizer.handleEvent
package:flutter/…/gestures/monodrag.dart:289
flutter: #18     PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:93
flutter: #19     PointerRouter._dispatchEventToRoutes.<anonymous closure>
`

Thanks for your work on this great flutter package! Hope this issue can get sorted somehow, I can take a look on it by myself as soon as I have time but I'm currently very busy at work. Maybe the user who implemented the feature can take a look.

Thanks and best regards,
Peter

**Comment by peter9teufel** [comment]
I quickly forked the repo to do some further investigation of my issue and here is the outcome:
In our app's UI the widget containing the sticky header table got rebuilt while the other page was already pushed to the Navigator, that somehow resulted in a stage where the sticky header table lost the relation scrollviews <--> scrollcontrollers as the scrollview where not visible on screen.
The issue could be fixed by not rendering the table while pushing the other view and rerendering when the popup is closed. The previous version without the ability to have custom scroll controllers seems to properly reattach the scroll controllers to the views in the described scenario. 

Thus I'm closing this issue as I don't consider this as a bug because the changed implementation simply requires different UI handling to fix the problem.

Thanks and keep up the good work

**Comment by u2tall** [comment]
Hello, 
Thanks so much for posting this. I'm having the same issue and I thought I must've been doing something wrong but couldn't figure it out. 
I'm very new to flutter, so I'm having trouble understanding how exactly you implemented your fix. If it's at all possible, I would greatly appreciate clarification.
