### ISSUE TITLE
Where to add Row and Column list?

### ISSUE THREAD

**Issue by zyllus17** [AlexBacich/sticky-headers-table#3]
Suppose I have this row and column -->
```
final List<String> titleColumn = [
  'Name',
  'Nation',
  'Population',
]; 
```

```
class City {
  final String name;
  final String nation;
  final int population;

  const City({
    @required this.name,
    @required this.nation,
    @required this.population,
  });
}

```
```
final List<City> titleRow = [
  City(name: 'Chongqing', nation: 'China', population: 30751600),
  City(name: 'Shanghai', nation: 'China', population: 24256800),
  City(name: 'Beijing', nation: 'China', population: 21516000),
  City(name: 'Lagos', nation: 'Nigeria', population: 16060303),
  City(name: 'Chengdu', nation: 'China', population: 16044700),
  City(name: 'Karachi', nation: 'Pakistan', population: 14910352),
  City(name: 'Dhaka', nation: 'Bangladesh', population: 14399000),
];
```

Where should I add my list to get the data like this in the example/main.dart of your repository--->

![Screenshot_1582914664](https://user-images.githubusercontent.com/50977126/75576888-d3938780-5a86-11ea-8d8c-6c33b38daa2a.png)

**Comment by zyllus17** [comment]
I have made the rows and column as I want them to be but how do I add the values like the Population  will have different numbers, the nation will have different values etc

**Comment by zyllus17** [comment]
![Screenshot_1583164682](https://user-images.githubusercontent.com/50977126/75694082-f82d7080-5ccd-11ea-9529-50a0e176191c.png)

So this is my project, It is basically a fees structure and all the values will be in number. I have marked the issues in the image as clearly as possible to help you understand what I want to achieve and where.

1. I want to add red lines separating each column and row as you have shown in the gif of the readme.md file.

2. I want to add different values inside the rows and columns. You have a loop in the app to get all the values but every value that I have is different so how do I put each value in respective set?

3. The long texts are getting adjusted in the row and column and are not visible, how do I make them fall in the row/ column below.(For eg if the word is too long, it gets pushed in the line below like the Wrap widget does)

**Comment by AlexBacich** [comment]
1. Red lines - look at example here: https://github.com/AlexBacich/sticky-headers-table/blob/master/example/decorated_example.dart
2. Fill values inside rows and columns. You should use two-dimension array.  
List of rows, while each row is a list of values in table. 
```
  List<List<String>> _makeData() {
    final List<List<String>> output = [];
    for (int i = 0; i < columns; i++) {
      final List<String> row = [];
      for (int j = 0; j < rows; j++) {
        row.add('T$i : L$j');
      }
      output.add(row);
    }
    return output;
  }
```

3. Adjusting long texts. I don't believe it's possible to make text fall in the row\column below. This structure doesn't support. 
However you can adjust size of cells. It's possible in parameters.

**Comment by zyllus17** [comment]
I understood how to get No.1 issue sorted.

I still can't get how to sort out Issue 2.
 Can you please show me an implementation of List<List<String>> with this data: 
![image](https://user-images.githubusercontent.com/50977126/76161051-aebda500-6155-11ea-843e-e105c77636ef.png)
If you show me the implementation, I will edit it with my own data.

The issue 3 still persists. The `CellDimension` value doesn't increase the length of the column and rows but it just adjusts the data inside, making the text smaller when I increase the value.

**Comment by AlexBacich** [comment]
As for #2 - here you go: 

```
 final List<List<String>> sampleData = [
    ['Lagos', 'Nigeria', '16060303'],
    ['Lagos', 'Nigeria', '16060303'],
    ['Karachi', 'Pakistan', '14910352'],
  ];
```

Once you put real data - please send entire code including changes to CellDimensions so I can take a look.

**Comment by zyllus17** [comment]
I have added `TODO `to help you figure out the issues in the code.

https://github.com/zyllus17/Aliah-fees-table-flutter

**Comment by AlexBacich** [comment]
I should have mentioned this in description. To make table cells resize you need to do one more thing. 

In StickyHeadersTable itself there is parameter cellDimensions. You need to fullfill them with same dimensions as you did for table cells. (what you did for table cells themselves seems OK and should be kept too).
