### ISSUE TITLE
ScrollController not attached to any scroll views - When resizing in Windows

### ISSUE THREAD

**Issue by corusm** [AlexBacich/sticky-headers-table#31]
Hi, I have the issue, that the Scrollcontroller will be not attached, when resizing the window in Windows. 

```dart
class Edit extends StatefulWidget {
  @override
  _EditState createState() => _EditState ();
}

class _EditState extends State<Edit > {
  final columns = 17;
  final rows = 20;

  /// Simple generator for column title
  List<String> makeTitleColumn() =>
      List.generate(columns, (i) => 'Position $i');

  /// Simple generator for row title
  List<String> makeTitleRow() => List.generate(rows, (i) => 'Ort $i');
  List<List<String>> makeData() {
    final List<List<String>> output = [];
    for (int i = 0; i < columns; i++) {
      final List<String> row = [];
      for (int j = 0; j < rows; j++) {
        row.add('${j + i}');
      }
      output.add(row);
    }
    return output;
  }

  // When changing Window size Scrollcontroller detatch

  @override
  Widget build(BuildContext context) {
    return Container(
      width: MediaQuery.of(context).size.width,
      height: MediaQuery.of(context).size.height - 163,
      child: StickyHeadersTable(
        columnsLength: makeTitleColumn().length,
        rowsLength: makeTitleRow().length,
        columnsTitleBuilder: (i) => Text(makeTitleColumn()[i]),
        rowsTitleBuilder: (j) => Text(makeTitleRow()[j]),
        contentCellBuilder: (k, l) => Text(makeData()[k][l]),
        legendCell: Text('Aufmaßblatt 1'),
      ),
    );
  }
}
```

**Comment by ibergman** [comment]
I have the same issue when I filter the data

**Comment by botty87** [comment]
Me too, but I solved the problem. I've forked the library and then, in the table_sticky_headers.dart file, go to che _StickyHeadersTableState class.
I moved the part:

> _verticalSyncController = _SyncScrollController([
      widget.scrollControllers._verticalTitleController,
      widget.scrollControllers._verticalBodyController,
    ]);
    _horizontalSyncController = _SyncScrollController([
      widget.scrollControllers._horizontalTitleController,
      widget.scrollControllers._horizontalBodyController,
    ]);

from the initState to the build method.

I hoe it could be useful also for the maintainers for an update!

**Comment by pMertDogan** [comment]
Can you share your repo? We can use it as workaround

**Comment by seena98** [comment]
> Me too, but I solved the problem. I've forked the library and then, in the table_sticky_headers.dart file, go to che _StickyHeadersTableState class. I moved the part:
> 
> > _verticalSyncController = _SyncScrollController([
> > widget.scrollControllers._verticalTitleController,
> > widget.scrollControllers._verticalBodyController,
> > ]);
> > _horizontalSyncController = _SyncScrollController([
> > widget.scrollControllers._horizontalTitleController,
> > widget.scrollControllers._horizontalBodyController,
> > ]);
> 
> from the initState to the build method.
> 
> I hope it could be useful also for the maintainers for an update!

This Solution Solved the problem. Thanks a lot.

**Comment by xyzbilal** [comment]
in my experience hot reload causes this problem. to avoid it I added uniqekey and problem solved;
```
StickyHeadersTable(
    key: UniqueKey(),
     initialScrollOffsetX: 0.0,
  initialScrollOffsetY: 0.0,
          columnsLength:...
```

**Comment by izi4ever** [comment]
It will fixed in today update.

**Comment by AlexBacich** [comment]
Update 2.0.2 available, closing.
