### ISSUE TITLE
want to always display scrollbars in flutter web

### ISSUE THREAD

**Issue by yokoi-engineering** [AlexBacich/sticky-headers-table#32]
I want to always display vertical and horizontal scrollbars in flutter web.

I want the scroll bar to be displayed on a PC that cannot be touched, unlike the smartphone app.

Is it possible to deal with it?

**Comment by AlexBacich** [comment]
This may help: 
https://api.flutter.dev/flutter/material/Scrollbar/thumbVisibility.html
