### ISSUE TITLE
Column widths as percentages

### ISSUE THREAD

**Issue by redeyedvireo** [AlexBacich/sticky-headers-table#36]
Is there a way to specify column widths as percentages of the total widget width?  If not, can this be added as a feature request?  Ideally, it would be great to be able to use a combination of fixed sizes and percentages.

The issue I'm running into is that when the user resizes the window, the table doesn't resize.  I'll need to calculate the column widths based on the total widget size, which isn't a problem, but obtaining widget size in Flutter is not straight-forward.  I'm running the app on Windows, so the app window is resizable.

**Comment by karmarcharger** [comment]
Inside 
Widget build(BuildContext context) {
double width = MediaQuery.of(context).size.width; //finds width of media , I tested on android and chrome no problem
Column(children:[Expanded(child:
                StickyHeadersTable(
              **cellDimensions: CellDimensions.uniform(width: (width/(COLUMNLIST.length+1)), height: 50)**
               //+1 because last column not show without it
)
)
])

![ezgif com-gif-maker](https://user-images.githubusercontent.com/10364143/133582716-a624ea9d-e255-4e4e-8987-05e80d9d58f3.gif)

**Comment by AlexBacich** [comment]
Added new tab with example. Enjoy :)
