### ISSUE TITLE
ScrollController not attached to any scroll views.

### ISSUE THREAD

**Issue by JatinSpectus** [AlexBacich/sticky-headers-table#37]
Hi
When I add or remove data from row and column and data list in set State and after refreshing scrolling is not working. Sticky Row is not scrolling horizontally.

Here is the error

ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 171 pos 12: '_positions.isNotEmpty'

When the exception was thrown, this was the stack: 
#2      ScrollController.jumpTo (package:flutter/src/widgets/scroll_controller.dart:171:12)
#3      _SyncScrollController.processNotification (package:login_demo/scrollviewClasses/table_sticky_headers.dart:348:22)
#4      _StickyHeadersTableState.build.<anonymous closure> (package:login_demo/scrollviewClasses/table_sticky_headers.dart:272:51)
#5      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4045:39)
#6      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:138:13)
...
The AnimationController notifying listeners was: AnimationController#bf7f9(⏭ 115.035; paused; for BallisticScrollActivity)

**Comment by alenpmla** [comment]
Same issue for me. I had reverted to an older version ^1.1.2 inorder to fix this issue.

**Comment by nhanta0408** [comment]
I also have this issue, is there any update?

**Comment by evalsxonted** [comment]
same issue for me

**Comment by AlexBacich** [comment]
Update 2.0.2 available, closing.
