### ISSUE TITLE
headers sometimes become too sticky

### ISSUE THREAD

**Issue by yamadaba** [AlexBacich/sticky-headers-table#38]
When I run Tap Handler example on my Android phone (Sharp SH-M04), I found a behavior which is probably different from what is  expected.  Indeed, when I tap on a cell in the Tap Handler example, the column and the row including the cell are highlighted as is expected.  However, after that, sticky columns and rows appear to become too sticky, i.e., they become fixed and no longer synchronize with the movement of the cells, which appears to be different from what is expected.

**Comment by yamadaba** [comment]
It was not intended to use large bold fonts for posting my message.  Indeed, what I only did was to use multiple '=' characters as a separator.  Please never mind about it.

**Comment by vcenturion** [comment]
You can remove this line from the build and set it as a class variable
      final ScrollControllers myScrollControllers = ScrollControllers(); // modified

**Comment by AlexBacich** [comment]
This problem doesn't exist anymore since 2.0.2
