### ISSUE TITLE
Two-dimensional arrays index notation

### ISSUE THREAD

**Issue by deadsoul44** [AlexBacich/sticky-headers-table#4]
Hello,

Thanks for the great package. 
Index notation for contentCellBuilder could be the opposite. First index is row and the second index is column.

https://en.wikipedia.org/wiki/Index_notation#Two-dimensional_arrays

**Comment by AlexBacich** [comment]
Hey, thanks for feedback. 

You are right. I realized this too late and didn't want to change since package is already released this way. 

Since index notation isn't usable anyway - I'm thinking to switch to builder as in flutter tables.

**Comment by AlexBacich** [comment]
Changed inner descriptions of i \ j to be more clear. I think that's all I can do for now without breaking users logic.
