### ISSUE TITLE
Disable scroll

### ISSUE THREAD

**Issue by callmejm** [AlexBacich/sticky-headers-table#41]
How can I disable vertical scroll, because parent is Single Child Scroll View

**Comment by AlexBacich** [comment]
@callmejm , do you want to prohibit user to scroll vertically? Or do you want to simply hide scrollbar? 
If prohibiting vertical scroll I don't see much sense for it, unless I'm missing anything. 
If hiding Scrollbar - please file a new ticket or suggest a PR. 
Thanks for your input!
