### ISSUE TITLE
add border for table, change background for header

### ISSUE THREAD

**Issue by antonydieu** [AlexBacich/sticky-headers-table#44]
I can't add border for table, also i can't change background for header. Please help me
<img width="370" alt="border" src="https://user-images.githubusercontent.com/5988428/154408830-b31f5906-f1e2-4b7e-a767-6180cb738a9f.png">

**Comment by AlexBacich** [comment]
@antonydieu , thanks for your interest to the library. Please look into Example > DecoratedTablePage. It has borders and custom backgorund.
