### ISSUE TITLE
Schedular Binding Issue

### ISSUE THREAD

**Issue by Sadja18** [AlexBacich/sticky-headers-table#47]
While trying to test the app in debug mode (and while building the apk), I encountered the following message in the Debug console.
(My flutter SDK version: 3.0.1, Android API level 30,)
`/C:/flutter/.pub-cache/hosted/pub.dartlang.org/table_sticky_headers-2.0.0/lib/table_sticky_headers.dart:115:22: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1`

Could I go ahead and remove Null check operation in the table_sticky_headers.dart file?

**Comment by AlexBacich** [comment]
Merged, update will be added shortly.
