### ISSUE TITLE
Remove FittedBox and BoxFit

### ISSUE THREAD

**Issue by deadsoul44** [AlexBacich/sticky-headers-table#5]
Hello,

Thanks again for the great package.

I think there is no need for FittedBox as all FittedBoxes are wrapped in containers. If someone wants to have it, it can be easily added. 

Due to FittedBox, I cannot wrap text.

**Comment by santhavathi** [comment]
Hello, My sticky row and column are of varying length and boxfit is not giving a proper look.
Can you please make the change to accomodate  varying length text for the sticky row and column.

**Comment by AlexBacich** [comment]
Thanks @deadsoul44  and @santhavathi ,

You are absolutely right - FittedBox isn't required and should be added as part of decoration strategy. 

Removed and preparing update.
