### ISSUE TITLE
better to add params for width, and add callback onTap for each row.

### ISSUE THREAD

**Issue by zinwalin** [AlexBacich/sticky-headers-table#7]
what do you think?

**Comment by AlexBacich** [comment]
You can add onTap for each cell in a row, including title cell. See this for example: 
https://github.com/AlexBacich/sticky-headers-table/blob/master/example/tap_handler.dart

As for width \ height - you can set them too. See this example: 
https://github.com/AlexBacich/sticky-headers-table/blob/master/example/decorated_example.dart
