### ISSUE TITLE
iOS issue

### ISSUE THREAD

**Issue by Tamerlanchiques** [AlexBacich/sticky-headers-table#8]
On iOS there is another way of implementing overscroll effect than on android.
All is OK until we get to end of row or column but then we can see glitches.

[Demo of issue](https://cdn.discordapp.com/attachments/392763474691883008/718507145892462612/sticky_lags.mp4)

**Comment by AlexBacich** [comment]
Thanks for reporting and sorry for delay. Yes, I've seen the issue but decided not to touch it. Honestly I don't know what to do with it. Guess need to play around with Physics class and write custom implementation to it. Not ready to do it any time soon.

**Comment by AlexBacich** [comment]
Solution is here:

https://github.com/AlexBacich/sticky-headers-table/issues/19
